//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmcExcelScheduleSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepareScheduleRemark_PMC
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string pmc_remark { get; set; }
        public int lineType_id { get; set; }
    
        public virtual LineType LineType { get; set; }
    }
}
