//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PmcExcelScheduleSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTb_WorkTime
    {
        public int id { get; set; }
        public string modelName { get; set; }
        public string floorName { get; set; }
        public string speOwnerName { get; set; }
        public string eeOwnerName { get; set; }
        public string qcOwnerName { get; set; }
        public Nullable<decimal> assy { get; set; }
        public Nullable<decimal> t1 { get; set; }
        public Nullable<decimal> t2 { get; set; }
        public Nullable<decimal> t3 { get; set; }
        public Nullable<decimal> t4 { get; set; }
        public Nullable<decimal> packing { get; set; }
        public Nullable<decimal> preAssy { get; set; }
        public Nullable<int> assyPeople { get; set; }
        public Nullable<int> packingPeople { get; set; }
        public Nullable<decimal> packingLeadTime { get; set; }
    }
}
